#!/bin/bash

#   Wi-fi access point creator.
#
#  Copyright 2007-2020 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <https://www.gnu.org/licenses/>.
#
##

#
#  Special thanks to
#  Josphat Mutai
#  https://computingforgeeks.com/create-wi-fi-hotspot-on-ubuntu-debian-fedora-centos-arch/
#  November 19, 2019
#
##

PS4="+:$( basename \"\${0}\" ):\${LINENO}: "
set -eu
if [ "${*}" != "${*/--verbose/}" ] ; then
    set -x
fi

declare -r iface_name="${1:-wls3}"
declare -r nm_connection="$( hostname )-ap"
declare -r pw="$( makepasswd )"

###
##
#

if ! ip addr | egrep "[[:space:]]${iface_name}:[[:space:]]" ; then
    echo "INFO:${0}:${LINENO}: Available network interfaces:" >&2
    ip addr | egrep "^[0-9]:[[:space:]]" >&2
    set +x
    echo "ERROR:${0}:${LINENO}: there is no such interface '${iface_name}'. Available ones are above." >&2
    exit 1
fi

ip link show
iw list

nmcli con add \
            type wifi \
            ifname "${iface_name}" \
            con-name "${nm_connection}" \
            autoconnect "yes" \
            ssid "${nm_connection}"

nmcli con modify \
            "$nm_connection" \
            802-11-wireless.mode \
            ap \
            802-11-wireless.band \
            bg \
            ipv4.method \
            shared

nmcli con modify "${nm_connection}" wifi-sec.key-mgmt wpa-psk
nmcli con modify "${nm_connection}" wifi-sec.psk "${pw}"

for idx in $( seq 1 3 ) ; do  # Activation may fail by timeout. Thus - retry (or wait).
    if nmcli con up $nm_connection ; then
        break
    fi
done
set +x

echo "INFO:${0}:${LINENO}: AP is '${nm_connection}'. Password: ${pw}" >&2
read -p "Press Enter to delete connection '${nm_connection}'."
set -x

nmcli con delete "${nm_connection}"

set +x
echo "INFO:${0}:${LINENO}: Job done."
echo ""
