#!/bin/bash
#
#  Copyright 2007-2025 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <https://www.gnu.org/licenses/>.
#
##

#
#  Remove/replace a symbols from/in file name: apt-get install rename
#
##

PS4="+:${0}:\${LINENO}: "
set -eu
#if [[ "${*}" =~ (^|[[:space:]])(--verbose|-v)([[:space:]]$) ]] ; then set -x ; fi

if [ -z "${*}" ] ; then
    "ERROR:${0}:${LINENO}: A file path expected as the CLI arguments." >&2
    exit 1
fi

if [ -e ~/.config/cleanfn/conf.txt ] ; then
    while read regex ; do
        if [[ "${regex}" =~ ^# ]] ; then
            continue
        elif [ -n "${regex}" ] ; then
            echo rename "${regex}" "${@}"
        fi
    done < <( cat ~/.config/cleanfn/conf.txt )
else
    rename 's/[[:space:]]/_/g' "${@}"
fi

true : Job done.
