#!/bin/bash

PS4="+:\${0}:\${LINENO}: "
set -xu

XRDP_SESSION="${XRDP_SESSION:-NotSet}"


declare -a panel_sides_pool=()

# Use '--secondary' when no need in main panel.
# The main panel will be skipped.
if [[ ! "${*}" =~ (^|[[:space:]])(--secondary|-s)([[:space:]]|$) ]] ; then
    panel_sides_pool+=("TOP")
fi


if [ "${XRDP_SESSION}" == "1" ] ; then
    session_type=REMOTE
    panel_sides_pool+=("RIGHT")
else
    session_type=ALL-WM
    panel_sides_pool+=("LEFT")
fi


for side in "${panel_sides_pool[@]}" ; do
    nohup fbpanel \
        --profile \
            "${USER}.$(hostname)_${session_type}_MAIN_${side}_fbPanel-6-1.conf" \
                2>/dev/null 1>/dev/null &
done
