#!/bin/bash
#
#  Copyright 2007-2019 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <http://www.gnu.org/licenses/>.
#
##

PS4="+:\$( basename \"\$( readlink -f "\${0}" )\" ):\${LINENO}: "
set +x -eu

read dt seconds tz <<< "$( date '+%Y-%m-%d-%H%M %S.%N %z' )"
tz="${tz//+/p}"
tz="${tz//-/m}"
echo -n "${dt}${tz}"
