#!/bin/bash
#
#  Copyright 2007-2025 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <https://www.gnu.org/licenses/>.
#
##

PS4="+:${0}:\${LINENO}: "
set -eu
if [[ "${*}" =~ [[:space:]]--verbose([[:space:]]|$) ]] ; then set -x ; fi

declare -r git_url="${1?Git URL not specified at CLI.}"

if [[ "${git_url}" =~ \.git$ ]] \
    && whiptail \
            --yesno \
            --defaultno \
            --backtitle "git clone ${git_url}" \
            --title "question" \
            "Strip '.git' at right?" \
            8 40
then
    modif_suffix='s#\.git$##'
fi

declare -r modif='s#^https://##;s#^git\@##;s#\:#/#'";${modif_suffix:-}"

declare -r d_clone="$( sed "${modif}" <<< "${git_url}" )"

if [ -d "${d_clone}" ] ; then
    set +x
    echo "ERROR:${0}:${LINENO}: Already exist '${d_clone}'." >&2
    exit 1
else
    mkdir -p "${d_clone}"
    git clone "${git_url}" "${d_clone}"
fi

true : Job done. >&2
