#!/bin/bash
#
#  Copyright 2007-2025 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <https://www.gnu.org/licenses/>.
#
##

f_order_short="images-order.txt"
f_prefix_short="name-prefix.txt"
help_text="Put images files names into text file '${f_order_short}' in the directory with images, one name per line. Put output-file name prefix into file '${f_prefix_short}'."
if [[ "${*}" =~ (^|[[:space:]])--help|-h([[:space:]]|$) ]] || [ "${#}" == "0" ] ; then
    echo "${help_text}"
    cat "${0}" | egrep "^[[:space:]]{1,}(-[a-zA-Z]{1,}|--[a-zA-Z\|\-]{1,}))"
    exit
fi

PS4="+:${0}:\${LINENO}: "
set -eu
if [[ "${*}" =~ (^|[[:space:]])--verbose([[:space:]]|$) ]] ; then
    set -x
    opt_verbose="--verbose"
fi

###
##
#

function reduce_img {
    set -eu
    f_in="${1}"
    f_out="${2}"
    trap "echo ERROR:${0}:${LINENO}: Fail while processing of '${f_in}'. >&2" ERR
    echo "INFO:${0}:${LINENO}: Processing in background '${f_in}'..." >&2
    convert -quality "${jpeg_quality}" "${f_in}" "${f_out}"
    sync "${f_out}"
    echo "INFO:${0}:${LINENO}: Converted $( du -hs "${f_in}" | tr -d '\n' )  ->  $( du -hs "${f_out}" | tr -d '\n' )." >&2
}


function get_tmp_name {
    local dir_name_as_prefix="${1}"
    local file_name="${2}"
    local tmp_name
    local suffix

    file_name="$( basename "${f}" )"  # TODO - work with tree of files.
    #test -n "${file_name}"  # No sense to check here due to this function is child process.
    suffix="${f##*\.}"
    tmp_name="${dir_name_as_prefix}/${file_name/%.$suffix}.tmp.${suffix}"
    #test -n "${tmp_name}"  # No sense to check here due to this function is child process.
    echo -n "${tmp_name}"
}


function align_names {
    local -r f_main="${1?File name of a file with list of target file names is not specified.}"
    local -r prefix="${2?Output prefix for file names is not specified.}"
    local -r f_obsolete="${f_main}.$( date '+%Y-%m-%d-%H%M-%S.%N' )-$( date '+%z' | sed 's/+/p/g;s/-/m/g' )"
    local    f
    local -i idx
    local    f_name_new
    local    suffix

    echo "INFO:${0}:${LINENO}: Aligning file names." >&2

    cp "${f_main}" "${f_obsolete}"
    trap "cp '${f_obsolete}' '${f_main}'" ERR
    echo -n "" > "${f_main}"
    idx=0
    while read f ; do
        idx+=1
        f_name_new="${output_name_prefix}-$( printf "%03d" ${idx} ).${f##*\.}"
        echo "${f_name_new}" >> "${f_main}"
        if [ -f "${f_name_new}" ] ; then
            echo "WARNING:${0}:${LINENO}: Already exist '${f_name_new}'. Skipping" >&2
        else
            mv -v "${f}" "${f_name_new}"
        fi
    done < <( cat "${f_obsolete}" )
}

###
##
#

req_names_align="false"
while [ "${#}" != 0 ] ; do
    arg_name="${1%%=*}"
    arg_value="${1#*=}"
    case "${arg_name}" in
    --align-names)      # Rename image files by template.
        declare -r req_names_align="true"
        ;;
    --jpeg-quality|-q)  # JPEG quality: use 'keep', or above 0 and below or equal 100. '0' is undocumented in 'man convert'.
        declare -r jpeg_quality="${arg_value,,}"
        ;;
    --verbose|--help)   # Other options.
        true
        ;;
    *)
        set +x
        echo "ERROR:${0}:${LINENO}: Unknown argument '${arg_name}'." >&2
        exit 1
    esac
    shift
done

###
##
#

if [ -z "${jpeg_quality:-}" ] ; then
    declare -r jpeg_quality="100"
fi

declare -r f_order_short="images-order.txt"
declare -r f_prefix_short="name-prefix.txt"

for f in "${f_order_short}"  "${f_order_short}" ; do
    if [ ! -r "${f}" ] || [ ! -s "${f}" ] ; then
        set +x
        echo "ERROR:${0}:${LINENO}: File '${f_order_short}' can not be read or can not be empty." >&2
        exit 1
    fi
done

declare -r output_name_prefix="$( cat "${f_prefix_short}" )"
if [ -z "${output_name_prefix}" ] ; then
    set +x
    echo "ERROR:${0}:${LINENO}: Prefix from '${f_prefix_short}' can not be empty." >&2
    exit 1
fi

if [ "${req_names_align}" == "true" ] ; then
    align_names "${f_order_short}" "${output_name_prefix}"
fi

declare -r f_pdf_out="${output_name_prefix}.pdf"

declare -r dir_tmp="$( mktemp --directory "/dev/shm/$( basename "${0}" )-XXXXXXXX" )"
trap "if [ -n '${opt_verbose:-}' ] ; then set -x ; fi \
        ; PS4='+:${0}:${LINENO}:TRAP: ' \
        ; if [ -n '${dir_tmp}' ] ; then rm -rf '${dir_tmp}' ; fi" \
            ERR EXIT INT TERM QUIT HUP

declare -a ordered_f_names_input=()
while read f ; do
    if [ -z "${f}" ] ; then
        set +x
        echo "ERROR:${0}:${LINENO}: File name can not be empty (see content of '${f_order_short}')." >&2
        exit 1
    fi
    ordered_f_names_input+=("${f}")
done < <( cat "${f_order_short}" )

declare -a ordered_f_names_tmp=()


for f in "${ordered_f_names_input[@]}" ; do
    ordered_f_names_tmp+=( "$( get_tmp_name "${dir_tmp}" "${f}" )" )
    for i in "${f}" "${ordered_f_names_tmp[-1]}" ; do
        if [ -z "${i}" ] ; then
            set +x
            echo "ERROR:${0}:${LINENO}: File name can not be empty." >&2
            exit 1
        fi
    done
done

if [[ "${jpeg_quality,,}" =~ ^keep|100$ ]] ; then
    for i in "${!ordered_f_names_input[@]}" ; do
        cp \
            "$( readlink -f "${ordered_f_names_input[$i]}" )" \
            "${ordered_f_names_tmp[$i]}"  # TODO - 'ln -s' here?
    done
else
    declare -a childs=()
    for i in "${!ordered_f_names_input[@]}" ; do
        reduce_img "${ordered_f_names_input[$i]}" "${ordered_f_names_tmp[$i]}" &
        childs+=("${!}")
    done
    error_level=0
    for pid in "${childs[@]}" ; do
        if ! wait "${pid}" ; then
            #echo "ERROR:${0}:${LINENO}: Had a fail." >&2
            error_level=1
        fi
    done
    wait
    [ "${error_level}" == "0" ] || exit 1
fi


##
#   In order to make it works do (security breach, https://bugs.archlinux.org/task/60580):
#       $ grep -rn '<policy' /etc | g -i pdf
#       /etc/ImageMagick-6/policy.xml:66:  <policy domain="resource" name="disk" value="16GiB"/>
#       /etc/ImageMagick-6/policy.xml:72:  <!-- <policy domain="module" rights="none" pattern="{PS,PDF,XPS}" /> -->
#       /etc/ImageMagick-6/policy.xml:94:  <!-- <policy domain="coder" rights="none" pattern="PDF" /> -->

echo "INFO:${0}:${LINENO}: Creating PDF..." >&2
convert "${ordered_f_names_tmp[@]}" "pdf:${f_pdf_out}"

set +x
echo "INFO:${0}:${LINENO}: PDF size is $( du -hs "${f_pdf_out}" | awk '{print $1}' )." >&2
echo "INFO:${0}:${LINENO}: Job done." >&2
