#!/bin/bash

#
#  Copyright 2007-2025 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <http://www.gnu.org/licenses/>.
#
##
#
#   FBPanel buttons with commands for scripting:
#
#       button {
#           #icon = gnome-session-halt
#           image = /usr/share/icons/gnome-session-halt.png
#           tooltip = Power state change - custom
#           action = lxterm -e 'bash -c "xscreensaver-command -lock && sleep 3 && sudo /home/.opt/sys-suspend"'
#       }
#       button {
#           #icon = gnome-session-halt
#           image = /usr/share/icons/gnome-session-halt.png
#           tooltip = Power state at LXDE
#           action = /usr/bin/lxsession-logout
#       }
#       button {
#           #icon = gnome-session-halt
#           image = /usr/share/icons/gnome-session-halt.png
#           tooltip = Power state at XFCE
#           action = /usr/bin/xfce4-session-logout
#       }
#       button {
#           #icon = gnome-session-halt
#           image = /usr/share/icons/gnome-session-halt.png
#           tooltip = Power state at LXQT
#           action = /usr/bin/lxqt-leave
#       }
#
##

PS4="+:\${0}:\${LINENO}: "
set -xeu

declare -r XDG_SESSION_DESKTOP="${XDG_SESSION_DESKTOP:-}"

case "${XDG_SESSION_DESKTOP}" in  # If the var. is not set, may export the var in '~/.xinitrc'.
    openbox_remote)
        if whiptail --yesno --defaultno --title " question " "End session?" 7 18 ; then
            openbox --exit
        fi
        ;;
    xfce)
        xfce4-session-logout
        ;;
    lxqt)
        lxqt-leave
        ;;
    *)
        echo "WARNING:${0}:${LINENO}: Unknown desktop environment '${XDG_SESSION_DESKTOP}'." >&2
        exit 1
        ;;
esac

set +x
echo "INFO:$( basename "${0}" ):${LINENO}: Job done." >&2
echo -ne "\n"
