#!/bin/bash

#
#  Copyright 2019-2022 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <https://www.gnu.org/licenses/>.
#
##

#
#   Consider to use 'systemctl restart NetworkManager.service'.
##

PS4="+:$( basename \"\${0}\" ):\${LINENO}: "
set -eu
if [ "${*}" != "${*/--verbose/}" ] ; then
    set -x
fi

declare -r shell_val_true=0
declare -r shell_val_false=1

function check_a_routes {
    local -r action="${1?Action not specified.}"
    local -i is_it
    local    invertor

    case "${action}" in
        absent)
            invertor="!"
            ;;
        present)
            invertor=""
            ;;
        *)
            echo "ERROR:$( basename "${0}" ):${LINENO}: Unknown action '${action}'." >&2
            exit $shell_val_false
    esac

    if [ ${invertor} -n "$( ip route show )" ] ; then
        is_it=$shell_val_true
    else
        is_it=$shell_val_false
    fi

    return $is_it
}

nmcli networking off
echo -n "INFO:$( basename "${0}" ):${LINENO}: Waiting for routes to be absent..." >&2
while check_a_routes present ; do echo -n . >&2 ; sleep 0.5 ; done ; echo

nmcli networking on
echo -n "INFO:$( basename "${0}" ):${LINENO}: Waiting for routes to be present..." >&2
while check_a_routes absent ; do echo -n . >&2 ; sleep 0.5 ; done ; echo

set +x
echo "INFO:$( basename "${0}" ):${LINENO}: Job done." >&2
echo ""
