#!/bin/bash
#
#  Copyright 2007-2024 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <https://www.gnu.org/licenses/>.
#
##

#
#   Configuration file example:
#       [
#           {
#               "hosts": [
#                   "127.0.0.1",
#                   "localhost"
#                   ],
#               "ports": [
#                   "22",
#                   "2222"
#                   ]
#           },
#           {
#               "hosts": ["a"],
#               "ports": ["22"]
#           }
#       ]
#
##

PS4="+:\$( basename \"\${0}\" ):\${LINENO}: "
set -eu
if [[ "${*}" =~ --verbose ]] ; then
    set -x
fi

declare -r f_cnf="${1:-${HOME}/.ssh/known-test-conns.json}"
echo "INFO:$( basename "${0}" ):${LINENO}: Using configuration file '${f_cnf}'." >&2

declare -t timeout_conn="5"  # In seconds.

declare -r d_tmp="$( mktemp --directory --tmpdir="/dev/shm" "$( basename "${0}" ).$$.XXXX" )"
declare -r file_err_log="${d_tmp}/error.log"
declare -r d_targets="${d_tmp}/targets"
trap "rm -rf '${d_tmp}'"  EXIT QUIT TERM ABRT INT  # KILL and STOP can't be intercepted.


###
##
#


function filter_availables {
    local hst="${1}"
    local prt="${2}"
    local dir_out="${3}"
    local f_out="${dir_out}/$( echo "${hst}:${prt}" | sha256sum | awk '{print $1}' ).targets"

    # Unreachable targets should not be reported.
    if timeout 1 nc -vz -w 1 "${hst}" "${prt}" 1>/dev/null 2>/dev/null
    then
        echo "processing_target ${hst} ${prt}" > "${f_out}"
        while read ip ; do
            if [ -n "${ip}" ] ; then
                echo "processing_target ${ip} ${prt}" >> "${f_out}"
            fi
        done <<< "$( cat /etc/hosts \
                            | grep -Ev '^[[:space:]]{0,}#' \
                            | grep -E "[[:space:]]{1,}${hst}([[:space:]]{1,}|$)" \
                            | awk '{print $1}' \
                            | sort \
                            | uniq )"

    else
        echo "WARNING:$( basename "${0}" ):${LINENO}: '${hst}:${prt}' is unreachable and is sckipped." >&2
    fi
}

function produce_targets_list {

    # TODO - Split targets lists by hostname only, instead of hostname+port.

    local -r d_out="${1}"
    local hst
    local prt

    mkdir -p "${d_targets}"

    while read hst prt ; do
        if [ -n "${hst}" ] && [ -n "${prt}" ] ; then
            filter_availables "${hst}" "${prt}" "${d_out}" &
        fi
    done <<< "$( jq \
                        -r \
                        '.[] | [.hosts[] + " " + .ports[]] | .[]' \
                        "${f_cnf}" \
                    | sort \
                    | uniq )"
    wait
}

function scan_targets {
    local -r f_in="${1}"
    local -r f_out="${f_in}.keys"
    while read marker host port ; do
        if [ -n "${host}" ] && [ -n "${port}" ] ; then
            scan_host "${host}" "${port}" "${f_out}"
            sleep 0.5  # Server does not answer reliably under a load.
        fi
    done < "${f_in}"
}

function scan_host {
    # OpenSSH server may not return all keys upon
    # 'ssh-keyscan -p ... -H ...' if the requests are performed at high
    # frequency. That's why requests by IP address and by host name of
    # that IP in parallel are not reliable. It's better to make
    # sequential requests to a same server.

    local -r hst="${1}"
    local -r prt="${2}"
    local -r f_out="${3}"
    #local    exit_code=0

    trap "echo ERROR:$( basename "${0}" ):${LINENO}: Smth. failed during scan of '${host}:${port}'. " >&2 ERR

    if timeout 2 ssh-keyscan \
                    -T "${timeout_conn}" \
                    -p "${prt}" -H "${hst}" \
                        >> "${f_out}" \
                        2>/dev/null
    then
        true : "${hst}:${prt}" has been scanned. >&2
    else
        message="ERROR:$( basename "${0}" ):${LINENO}: Failed to scan '${hst}:${prt}'."
        echo "${message}" >> "${file_err_log}"
        #exit_code=1
    fi
    return 0
}

function remove_host {
    local -r hst="${1}"
    local -r prt="${2}"
    #local    exit_code=0

    trap "echo ERROR:$( basename "${0}" ):${LINENO}: Smth. failed during remove of '${host}:${port}'. " >&2 ERR

    # Address specification example: [127.0.0.1]:12345
    # Removal will lead to race for '~/.ssh/known_hosts' in case of concurrency.
    if ssh-keygen \
        -f "${HOME}/.ssh/known_hosts" \
        -R "${hst}" \
            1>/dev/null \
            2>/dev/null
    then
        true : "${hst}:${prt}" has been removed. >&2
    else
        message="ERROR:$( basename "${0}" ):${LINENO}: Failed to remove '${hst}:${prt}' from known hosts."
        echo "${message}" >> "${file_err_log}"
        #exit_code=1
    fi
    return 0
}

###
##
#

touch "${file_err_log}"

if ! test -f "${f_cnf}" ; then
    echo "ERROR:$( basename "${0}" ):${LINENO}: Configuration file '${f_cnf}' is missed." >&2
    echo "Configuration file name: '${f_cnf}'.
Configuration file example:
[
   {
       \"hosts\": [
           \"127.0.0.1\",
           \"localhost\"
           ],
       \"ports\": [
           \"22\",
           \"2222\"
           ]
   },
   {
       \"hosts\": [\"abc\"],
       \"ports\": [\"22\"]
   }
]
"
    exit 1
fi

produce_targets_list "${d_targets}"

while read f_target ; do
    scan_targets "${f_target}" &
done < <( find "${d_targets}" -type f -name "*.targets" )
wait
sync "${d_targets}"

while read marker host port ; do
    if [ -n "${host}" ] && [ -n "${port}" ] ; then
        remove_host "${host}" "${port}"
    fi
done < <( find "${d_targets}" -type f -name "*.targets" )
sync "${d_targets}"

while read f ; do
    cat "${f}" >> "${HOME}/.ssh/known_hosts"
    sync "${HOME}/.ssh/known_hosts"
done < <( find "${d_targets}" -type f -name "*.keys" )

if [ "$( stat -c '%s' "${file_err_log}" )" == "0" ] ; then
    set +x
    echo "INFO:$( basename "${0}" ):${LINENO}: Job done." >&2
else
    set +x
    cat "${file_err_log}" >&2
    exit 1
fi
