#!/bin/bash
#
#  Copyright 2007-2024 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <https://www.gnu.org/licenses/>.
#
##

#
#   Configuration file example:
#       [
#           {
#               "hosts": [
#                   "127.0.0.1",
#                   "localhost"
#                   ],
#               "ports": [
#                   "22",
#                   "2222"
#                   ]
#           },
#           {
#               "hosts": ["a"],
#               "ports": ["22"]
#           }
#       ]
#
##

PS4="+:\$( basename \"\${0}\" ):\${LINENO}: "
set -eu
if [[ "${*}" =~ --verbose ]] ; then
    set -x
fi

declare -r f_cnf="${1:-${HOME}/.ssh/known-test-conns.json}"
echo "INFO:$( basename "${0}" ):${LINENO}: Using configuration file '${f_cnf}'." >&2

declare -t timeout_conn="5"  # In seconds.

declare -r d_tmp="$( mktemp --directory --tmpdir="/dev/shm" "$( basename "${0}" ).$$.XXXX.log" )"
declare -r file_err_log="${d_tmp}/error.log"
declare -r file_targets="${d_tmp}/targets.txt"
trap "rm -rf '${d_tmp}'"  EXIT QUIT TERM ABRT INT  # KILL and STOP can't be intercepted.


###
##
#


function check_availability {
    local hst="${1}"
    local prt="${2}"

    # Unreachable targets should not be reported.
    if timeout 0.2 nc -vz -w 1 "${hst}" "${prt}" 1>/dev/null 2>/dev/null
    then
        echo "processing_target ${hst} ${prt}"
        while read ip ; do
            if [ -n "${ip}" ] ; then
                echo "processing_target ${ip} ${prt}"
            fi
        done <<< "$( cat /etc/hosts \
                            | grep -Ev '^[[:space:]]{0,}#' \
                            | grep -E "${hst}" \
                            | awk '{print $1}' \
                            | sort \
                            | uniq )"
    else
        echo "WARNING:$( basename "${0}" ):${LINENO}: '${hst}:${prt}' is unreachable and is sckipped." >&2
    fi
}

function produce_targets_list {
    local hst
    local prt

    while read hst prt ; do
        if [ -n "${hst}" ] && [ -n "${prt}" ] ; then
            check_availability "${hst}" "${prt}" &
        fi
    done <<< "$( jq \
                        -r \
                        '.[] | [.hosts[] + " " + .ports[]] | .[]' \
                        "${f_cnf}" \
                    | sort \
                    | uniq )"
    wait
}

function scan_host {
    local -r hst="${1}"
    local -r prt="${2}"
    #local    exit_code=0

    trap "echo ERROR:$( basename "${0}" ):${LINENO}: Smth. failed during scan of '${host}:${port}'. " >&2 ERR

    if timeout 0.4 ssh-keyscan \
                    -T "${timeout_conn}" \
                    -p "${prt}" -H "${hst}" \
                        >> "${d_tmp}/$( sha256sum | awk '{print $1}' ).keys" \
                        2>/dev/null
    then
        true : "${hst}:${prt}" has been scanned. >&2
    else
        message="ERROR:$( basename "${0}" ):${LINENO}: Failed to scan '${hst}:${prt}'."
        echo "${message}" >> "${file_err_log}"
        #exit_code=1
    fi
    return 0  # Errors are collected. No stop on error.
}

function reload_host {
    local -r hst="${1}"
    local -r prt="${2}"
    #local    exit_code=0

    trap "echo ERROR:$( basename "${0}" ):${LINENO}: Smth. failed during reload of '${host}:${port}'. " >&2 ERR

    #   Address specification example: [127.0.0.1]:12345
    #   Removal will lead to race for '~/.ssh/known_hosts' in case of concurrency.
    if ssh-keygen \
        -f "${HOME}/.ssh/known_hosts" \
        -R "${hst}" \
            1>/dev/null \
            2>/dev/null
    then
        true : "${hst}:${prt}" has been removed. >&2
    else
        message="ERROR:$( basename "${0}" ):${LINENO}: Failed to remove '${hst}:${prt}' from known hosts."
        echo "${message}" >> "${file_err_log}"
        #exit_code=1
    fi

    while read f ; do
        cat "${f}" >> "${HOME}/.ssh/known_hosts"
    done < <( find "${d_tmp}" -type f -name "*.keys" )

    return 0  # Errors are collected. No stop on error.
}

###
##
#

if ! test -f "${f_cnf}" ; then
    echo "ERROR:$( basename "${0}" ):${LINENO}: Configuration file '${f_cnf}' is missed." >&2
    echo "Configuration file name: '${f_cnf}'.
Configuration file example:
[
   {
       \"hosts\": [
           \"127.0.0.1\",
           \"localhost\"
           ],
       \"ports\": [
           \"22\",
           \"2222\"
           ]
   },
   {
       \"hosts\": [\"abc\"],
       \"ports\": [\"22\"]
   }
]
"
    exit 1
fi

produce_targets_list \
                | grep processing_target \
                | sort \
                | uniq \
    > "${file_targets}"
while read marker host port ; do
    if [ -n "${host}" ] && [ -n "${port}" ] ; then
        scan_host "${host}" "${port}" &
    fi
done < "${file_targets}"
wait
sync "${d_tmp}"
while read marker host port ; do
    if [ -n "${host}" ] && [ -n "${port}" ] ; then
        reload_host "${host}" "${port}"
    fi
done < "${file_targets}"


if [ "$( stat -c '%s' "${file_err_log}" )" == "0" ] ; then
    set +x
    echo "INFO:$( basename "${0}" ):${LINENO}: Job done." >&2
else
    set +x
    cat "${file_err_log}" >&2
    exit 1
fi
