#!/bin/bash

PS4="+:$( basename "${0}" ):\${LINENO}: "
set -eu
if [[ "${*}" =~ --verbose ]] ; then set -x ; fi

declare -r dir_target="${1?Target directory not specified at CLI.}"

declare -r  f_this="${0##*/}"
declare -r  f_cnf="${HOME}/.config/script-crypt/${f_this%\.sh}.conf"

declare -rA types_default=(
                ["VID"]="video"
                ["IMG"]="photo"
                )

if [ ! -f "${f_cnf}" ] ; then
    mkdir -p "$( dirname "${f_cnf}" )"
    dict="\"types\": {"
    for k in "${!types_default[@]}" ; do
        dict+="\"$k\": \"${types_default[$k]}\", "
    done
    if [ "${dict: -2:2}" == ", " ] ; then  # If the dict was ever not empty.
        dict="${dict::-2}"  # Remove last coma to have correct JSON syntax.
    fi
    dict+="}"
    json="{${dict}}"
    echo "${json}" | jq --indent 4 . > "${f_cnf}"
fi

jq --indent 4 . "${f_cnf}" 1>/dev/null
json="$( jq --indent 4 . "${f_cnf}" )"
declare -A types=()
while read k v ; do
    types["${k}"]="${v}"
done < <( jq -r '
                .types |
                to_entries |
                map("\(.key) \(.value)") |
                .[] |
                "" + . + ""
            ' "${f_cnf}" )

###
##
#

function rename_it {
    local -r token="${1}"
    local -r f="${2}"
    local dn bn name ext new_name new_path
    dn="$( dirname "${f}" )"
    bn="$( basename "${f}" )"
    name="${bn%\.*}"
    ext="${bn##*\.}"
    new_name="$( sed "s/^${token}/file/" <<< "${name}" )"
    new_path="${dn}/${new_name}_${types[$token]}.${ext}"
    if [ -e "${new_path}" ] ; then
        exist+=("${new_path}")
        echo "ERROR:$( basename "${0}" ):${LINENO}: Already exist '${f}'" >&2
    else
        if ! mv "${f}" "${new_path}" ; then
            failed+=("${new_path}")
            echo "ERROR:$( basename "${0}" ):${LINENO}: Failed with '${f}'" >&2
        fi
    fi
}

if whiptail \
            --yesno \
            --defaultno \
            --yes-button recursive \
            --no-button "current only" \
            --backtitle " naming normaliser" \
            --title "QUESTION" \
            "Do the search recursive?" \
            "10" "50" 3>&1 1>&2 2>&3
then
    opt_maxdepth=""
else
    opt_maxdepth="-maxdepth 1"
fi

for t in "${!types[@]}" ; do
    while read f ; do
        if [ -z "${f}" ] ; then continue ; fi
        rename_it "${t}" "${f}" &
    done <<< "$( find \
                    "${dir_target}" \
                    ${opt_maxdepth} \
                    -name "${t}_*" )"
done
wait

set +x
echo "INFO:$( basename "${0}" ):${LINENO}: Job done." >&2
