#!/bin/bash

#
#  Copyright 2007-2020 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <http://www.gnu.org/licenses/>.
#
##

PS4="+:$( basename \"\${0}\" ):\${LINENO}: "
set -eu
set +x

if [ "${#}" -lt 0 ] || [ "${*}" != "${*/--help/}" ] ; then
    cat "${0}" | egrep "([[:space:]]|\|)[\-]{1,2}[a-zA-Z0-9_\-]{1,})"
    exit 1
fi

declare -r package_name="${1:-script-crypt}"

if which dpkg ; then
    dpkg -L "${package_name}"
else
    echo "ERROR:${0}:${LINENO}: Unsupported functionality call." >&2
    exit 1
fi

set +x
echo "INFO:$( basename "${0}" ):${LINENO}: Job done." >&2
echo -ne "\n"
