#!/bin/bash
#
#  Copyright 2007-2025 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <https://www.gnu.org/licenses/>.
#
##

PS4="+:${0}:\${LINENO}: "
set -eu
if [[ "${*}" =~ --verbose ]] ; then set -x ; fi

function umount_dir {
    local -r dir="${1}"
    if mountpoint --quiet "${dir}" ; then
        umount "${dir}"
    else
        umount_dir "$( dirname "${dir}" )"
    fi
    return
}

###
##
#

had_payload=false
while [ "${#}" != "0" ] ; do
    if [ -d "${1}" ] ; then
        umount_dir "$( cd "${1}" ; pwd )"
        had_payload=true
    fi
    shift
done

if [ "${had_payload}" == "false" ] ; then
    set +x
    echo "ERROR:${0}:${LINENO}: Specify an existent directory path as CLI argument(s)." >&2
    exit 1
fi

true : Job done. >&2
