#!/bin/bash


#
#  Copyright 2007-2014 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <http://www.gnu.org/licenses/>.
#
##


PS4="CMD:\${0}:\${LINENO}: "
set -x
set -e

declare -r true=0
declare -r false=0

declare -r predefinedConf="./predefined.conf"
declare -r autoGeneratedConf="./auto-generated.conf"
declare -r emptyConf="./empty.conf"

declare -r predefinedSect="test-section-name"
declare -r predefinedField="test-field-name"
declare -r predefinedValue="test-field-value"


function doErrorExit {
    local -r callerLineNo="${1}"
    local -r testName="${2}"
    set +x
    echo "ERROR:${0}:${callerLineNo}: Test '${testName}' failed." >&2
    exit ${false}
}

function testGetterFromPredefined {
    local result="$( ../../src/ConfFileSetGet.py \
        --action get \
        --file "${predefinedConf}" \
        --section "${predefinedSect}" \
        --key "${predefinedField}"
        )"
    if [ "${result}" == "${predefinedValue}" ] ; then
        return ${true}
    else
        doErrorExit "${LINENO}" "testGetterFromPredefined"
    fi
}

function testGetterFromEmpty {
    local result="$(../../src/ConfFileSetGet.py \
        --action get \
        --file "${emptyConf}" \
        --section "${predefinedSect}" \
        --key "${predefinedField}"
        )"
    if [ "${result}" == "" ] ; then
        return ${true}
    else
        doErrorExit "${LINENO}" "testGetterFromEmpty"
    fi
}

function testSetAndCreateNew {
    ../../src/ConfFileSetGet.py \
        --action set \
        --file "${autoGeneratedConf}" \
        --section "${predefinedSect}" \
        --key "${predefinedField}" \
        --value "${predefinedValue}"

    local result="$( ../../src/ConfFileSetGet.py \
        --action get \
        --file "${autoGeneratedConf}" \
        --section "${predefinedSect}" \
        --key "${predefinedField}"
        )"
    if [ "${result}" == "${predefinedValue}" ] ; then
        return ${true}
    else
        doErrorExit "${LINENO}" "testGetterFromPredefined"
    fi
}


testGetterFromPredefined
testGetterFromEmpty
testSetAndCreateNew

rm "${autoGeneratedConf}"

set +x
echo "INFO:${0}:${LINENO}: Tests done."
