#!/bin/bash

#
#  Copyright 2007-2025 Alex Vesev
#
#  This file is part of Script Crypt.
#
#  Script Crypt is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Script Crypt is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Script Crypt. If not, see <http://www.gnu.org/licenses/>.
#
##


PS4="+:\$( basename \"\$( readlink -f "\${0}" )\" ):\${LINENO}: "
set -eu -o pipefail
if [ "${#}" -lt 1 ] || [ "${*}" != "${*/--help/}" ] ; then
    cat "${0}" | egrep "([[:space:]]|\|)[\-]{1,2}[a-zA-Z0-9_\-]{1,})"
    exit 1
fi
if [ "${*}" != "${*/--verbose/}" ] ; then
    set -x
    OPT_VERBOSE="--verbose"
fi

declare -ri shell_val_true=0
declare -ri shell_val_false=1

###
##
#

function bt_shutdown {
    if TERM=xterm-256color whiptail \
            --yesno \
            --defaultno \
            --yes-button "BT OFF" \
            --no-button "cancel" \
            --backtitle " BT connector" \
            --title "SHUTDOWN BT" \
            "Switch BT off?" \
            "7" "26" 3>&1 1>&2 2>&3
    then
        /usr/sbin/rfkill block bluetooth
    fi
}

function ask_for_bt_wake_up {
    if [ "$( trigger-bt-state --show  ${OPT_VERBOSE:-} )" == "blocked" ]
    then
        if TERM=xterm-256color whiptail \
                --yesno \
                --defaultno \
                --yes-button "BT ON" \
                --no-button "cancel" \
                --backtitle " BT connector" \
                --title "ENABLE BT" \
                "Switch BT on?" \
                "7" "26" 3>&1 1>&2 2>&3
        then
            trigger-bt-state --switch ${OPT_VERBOSE:-}
        fi
    fi
}

function check_if_is_known_dev {
    local dev_conf_name="${1?Device name from configuration file is not specified.}"
    if [[ ! -v device_mac_pool["${dev_conf_name}"] ]] ; then
        set +x
        echo "ERROR:${0}:${LINENO}: Unknown device '${dev_conf_name}' for configuration file '${file_cnf}'. See '${0}' --help" >&2
        exit 1
    fi
}


function is_connected {
    local -r target_mac="${1?Device MAC address is not specified.}"

    bluez_version="$( bluetoothd -v )"
    if [ -z "${bluez_version}" ] ; then
        bluez_version="$( bluetoothctl --version )"
    fi

    function _is_connected {
        if dpkg --compare-versions "${bluez_version}" lt "5.65" ; then
            bluetoothctl info "${target_mac}" | grep -i --quiet 'Connected: yes'
        else
            bluetoothctl devices Connected | grep -i --quiet "${target_mac}"
        fi
    }

    if _is_connected ; then
        return ${shell_val_true}
    else
        return ${shell_val_false}
    fi
}

###
##
#

if [ "${*}" != "${*/--install/}" ] ; then

    if [ "$USER" == "root" ] ; then
        declare -r owner="${SUDO_USER}"
    else
        declare -r owner="${USER}"
    fi

    declare -r dir_this="$( cd "$( dirname "${0}" )" ; pwd )"
    declare -r file_this="${0}"
    declare -r file_cnf="$( getent passwd "$owner" | cut -d: -f6 )/.config/bt-connector/conf.json"

    if [ "${file_this}" != "/usr/bin/$( basename "${file_this}" )" ] ; then
        install --mode 755 --owner=root --group=root "${file_this}" /usr/bin
    fi
    if [ ! -f "/etc/bt-connector/conf.json" ] ; then
        install --directory --mode 755 --owner=root --group=root /etc/bt-connector/
        cat << EOF > /etc/bt-connector/conf.json
{
    "device": {
        "human-readable-name-A": "00:11:AA:BB:22:44",
        "human-readable-name-B": "CC:DD:55:66:EE:FF"
    }
}
EOF
        chmod 644       /etc/bt-connector/conf.json
        chown root:root /etc/bt-connector/conf.json
    fi
    if [ ! -f "${file_cnf}" ] ; then
        install --mode 755 --owner="${owner}" --group="${owner}" --directory "$( dirname "${file_cnf}" )"
        install --mode 600 --owner="${owner}" --group="${owner}" "${file_this}.json" "${file_cnf}"
    fi
    exit
fi

if [ "${*}" != "${*/--conf-file/}" ] ; then
    set +x
    echo "ERROR:${0}:${LINENO}: Unimplemented functionality call." >&2
    exit 1
else
    if [ -f ~/.config/bt-connector/conf.json ] ; then
        declare -r file_cnf="${HOME}/.config/bt-connector/conf.json"
    else
        if [ -f /etc/bt-connector/conf.json ] ; then
            declare -r file_cnf=/etc/bt-connector/conf.json
        else
            set +x
            echo "ERROR:$( basename "${0}" ):${LINENO}: Missed configuration file '/etc/bt-connector/conf.json'. You may try 'sudo \"${0}\" --install' to create the file." >&2
            exit 1
        fi
    fi
fi

jq . "${file_cnf}" 1>/dev/null  # Test configuration file syntax.

declare -A device_mac_pool=()
while read dev_name ; do
    device_mac_pool[$dev_name]="$( cat "${file_cnf}" | jq -r ".device.\"$dev_name\"" )"
done <<< "$( cat "${file_cnf}" | jq -r ".device | keys[]" )"  # cat "${file_cnf}" | jq -r ".device | to_entries[] | .key+\"=\"+.value"

op_status=0
while [ ${#} -gt 0 ] ; do
    arg_name="${1%%=*}"
    arg_value="${1#*=}"
    case "${arg_name}" in
        --list|--list-configured)
            if [ ! -v op_name ] ; then
                declare -r op_name="list-configured"
            fi
            ;;
        --list-known)
            if [ ! -v op_name ] ; then
                declare -r op_name="list-known"
            fi
            ;;
        -n|--name)
            d_name="${arg_value}"
            check_if_is_known_dev "${d_name:-}"
            ;;
        -c|--connect)
            if [ ! -v op_name ] ; then
                declare -r op_name="connect"
            fi
            ;;
        -r|--reconnect)
            if [ ! -v op_name ] ; then
                declare -r op_name="reconnect"
            fi
            ;;
        -d|--disconnect)
            if [ ! -v op_name ] ; then
                declare -r op_name="disconnect"
            fi
            ;;
        --disconnect-all)
            if [ ! -v op_name ] ; then
                declare -r op_name="disconnect-all"
            fi
        ;;
        --verbose)
            true
        ;;
        *)
            echo "ERROR:$( basename "${0}" ):${LINENO}: Got unknown argument '${arg_name}'." >&2
            exit 1
    esac
    shift
done


if [ "${op_name}" == "list-configured" ] ; then  # List devices by names known to this script.
    set +x
    echo "INFO:${0}:${LINENO}: Configuration file is '${file_cnf}'." >&2
    for name in "${!device_mac_pool[@]}"; do
        echo -n "$name"
        echo -ne "\t= "
        echo "${device_mac_pool[$name],,}"
    done
    exit
elif [ "${op_name}" == "list-known" ] ; then  # List devices as they are known for OS.
    set +x
    bluetoothctl devices
    exit
elif [ "${op_name}" == "connect" ] ; then
    ask_for_bt_wake_up

    for idx in $( seq 0 15 ) ; do
        if bluetoothctl connect "${device_mac_pool[$d_name]}" ; then
            op_status=0
            break
        else
            op_status=1
            sleep 0.5
        fi
    done
elif [ "${op_name}" == "reconnect" ] ; then

    function sleep_for {
        if ! type bc 1>/dev/null 2>/dev/null ; then
            return ${shell_val_true}
        fi
        local -r pb_cap="${1?Progress bar caption not set.}"
        local    pb_time="${2?Progress bar duration in seconds is not set.}"
        pb_time=$( bc <<< "${pb_time}*8" )
        local i
        for i in $( seq 1 "${pb_time}" ) ; do
            echo -ne "${pb_cap} $(printf "%0.s." $(seq 1 $i))\r"
            sleep 0.125
        done
        echo
    }

    if is_connected "${device_mac_pool[$d_name]}" ; then
        "${0}" --disconnect --name="${d_name}"
        sleep_for "Pause before connect" 2
        "${0}" --connect    --name="${d_name}"
    else
        "${0}" --connect    --name="${d_name}"
        sleep_for "Pause before disconnect" 0.5
        "${0}" --disconnect --name="${d_name}"
        sleep_for "Pause before connect" 2
        "${0}" --connect    --name="${d_name}"
    fi

elif [ "${op_name}" == "disconnect" ] ; then
    bluetoothctl disconnect "${device_mac_pool[$d_name]}" \
        || op_status=$?
elif [ "${op_name}" == "disconnect-all" ] ; then
    for mac in "${device_mac_pool[@]}" ; do
        bash -c "bluetoothctl disconnect '${mac}' || true" &
    done
    wait
    bt_shutdown
fi

if [ "${op_status}" != "0" ] ; then
    read -p "ERROR:${0}:${LINENO}: Had failure. Press Enter to continue..."
fi

set +x
echo "INFO:${0}:${LINENO}: Job done." >&2
